# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgPoFLdR_DsQyoW0P1S3UOW8CxbGChTJ
"""

from google import genai

# ضع مفتاح الـ API هنا (للتجربة فقط)
API_KEY = "AQ.Ab8RN6L_EIWBBFiNhodXm-Cd3B8QLWfxe20ej1m6fp8LWESUIw"

# إنشاء العميل
client = genai.Client(api_key=API_KEY)

# أدوات اختيارية
tools = [
    {
        "type": "google_search"
    }
]

# إعدادات التوليد
generation_config = {
    "temperature": 1,
    "top_p": 0.95,
    "max_output_tokens": 2048,
    "thinking_level": "high"
}

try:
    # إرسال السؤال إلى Gemini
    interaction = client.interactions.create(
        model="gemini-3.5-flash",
        input="اشرح لي ما هو الذكاء الاصطناعي بطريقة بسيطة.",
        tools=tools,
        generation_config=generation_config
    )

    # طباعة الرد
    print(interaction.output_text)

except Exception as e:
    print("حدث خطأ:")
    print(e)

